### ISSUE TITLE
Releaseが存在しない場合、Server Errorになる可能性がある

### ISSUE THREAD

**Issue by nitaking** [kouki-dan/git-issue-release#80]
## 起きたこと
`Server Error!`となる

## 状況
Releaseが存在しないままこのactionsを使用した。

## 試したこと
差分となるReleaseを作成した。
その場合、うまく動いたようにも見えます（詳しく調べきれてないまま https://github.com/x-motemen/git-pr-release で対応してしまったので、確証はないです）

## 提案したいこと
以下のいずれかの対応かなと。
- ドキュメントに前提作業として1stリリースの作成を明示する
- リリースが存在しない場合、エラーメッセージとしてわかりやすいものに変更する
- リリースが存在しない場合、initial commitを自動的に1st releaseにしてしまい、そこから差分を計算する

**Comment by kouki-dan** [comment]
Issueの登録ありがとうございます！手元で別のリポジトリを作って動作確認をしてみましたが、手元では動作しているようでした。GitHubのAPIがエラーを返すことがたまにあることは把握していて、おそらくそのケースであったと思います。

<img width="983" alt="スクリーンショット 2022-07-26 23 13 25" src="https://user-images.githubusercontent.com/1401711/181027640-345b7ad6-dc82-42b2-8d00-8a1cada93b8a.png">
<img width="983" alt="スクリーンショット 2022-07-26 23 13 39" src="https://user-images.githubusercontent.com/1401711/181027654-6499c2f6-9875-4985-911b-759d2002ace0.png">

対策としては、Releaseが存在しない場合に対応するのではなく、APIのリトライなどを検討しようと思います。このIssueはクローズさせていただきます。ご報告ありがとうございました！
